[workspace]
resolver = "2"
members = [
  "accessibility-rs",
  "accessibility-tree/victor",
  "accessibility-scraper",
  # internal
  "benches"
]

[workspace.dependencies]
smallvec = "1"
selectors = "0.22.0"
cssparser = "0.27.0"
html5ever = "0.27"
ego-tree = "0.6.2"
lazy_static = "1.4"