[workspace]
resolver = "2"
members = [
  "accessibility-rs",
  "accessibility-tree/victor",
  "accessibility-scraper"
]

[workspace.dependencies]
smallvec = "1"
selectors = "0.21.0"
cssparser = "0.25.0"
html5ever = "0.26"
ego-tree = "0.6.2"
lazy_static = "1.4"
