[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
accessibility-rs = { path = "../accessibility-rs" }

[[bench]]
name = "audit"
path = "audit.rs"
harness = false